### ISSUE TITLE
[Question] wich part of code cause prerendering on this project ?

### ISSUE THREAD

**Issue by julienGrd** [danroth27/BlazorWebAssemblyWithPrerendering#3]
Hi, I don't really understand wich part of your code cause prerendering ? (I also read https://chrissainty.com/prerendering-a-client-side-blazor-application/ but i don't find the answer)

for example, if i want disable prerendering on your project, what is the code i have to update ?

thanks !

**Comment by Infactum** [comment]
When using "regular" client-side blazor deployment your browser gets static html page from host, then it load `_framework / blazor.webassembly.js` script which downloads webassembly based C # runtime and renders page. Until blazor fully renders page, you see static html content which tupically is just a loading bar.
With server-side preloading backend hosts razor page (* .cshtml) insded of static one. This page renders view of your blazor apps and returns it to client. After this same JS / runtime preloading runs it background, but this time client sees normal page insted of login indicator.

Thats how we enable serving of razor pages.
https://github.com/danroth27/BlazorWebAssemblyWithPrerendering/blob/b7fe23d9cac5aeb1ade848efafa9e191af84acaa/BlazorWebAssemblyWithPrerendering.Server/Startup.cs#L47

And here is how prerendering starts inside razor page
https://github.com/danroth27/BlazorWebAssemblyWithPrerendering/blob/b7fe23d9cac5aeb1ade848efafa9e191af84acaa/BlazorWebAssemblyWithPrerendering.Server/Pages/_Host.cshtml#L17

**Comment by Franklin89** [comment]
The only "not so nice" thing about this is that you need to make sure that you have the implementation of the services both for the client and the server. See the `IWeatherForecastService`, that is implemented both in the Server project and on the client. This will always be required because if you navigate straight to the `/fetchdata` then the first page gets pre-rendered.

**Comment by julienGrd** [comment]
thanks for your response, I forgotten this issue, wich was opened on preview 7 or 8, with the latests release the distinction is really more clear. I can close this !
